# Generated by Django 3.2.2 on 2023-05-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
